//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNGod.Resource.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VNGod.Resource.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authorization 的本地化字符串。
        /// </summary>
        public static string Authorization {
            get {
                return ResourceManager.GetString("Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bangumi 的本地化字符串。
        /// </summary>
        public static string Bangumi {
            get {
                return ResourceManager.GetString("Bangumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bangumi ID: 的本地化字符串。
        /// </summary>
        public static string BangumiID {
            get {
                return ResourceManager.GetString("BangumiID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bangumi Token: 的本地化字符串。
        /// </summary>
        public static string BangumiToken {
            get {
                return ResourceManager.GetString("BangumiToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Before downloading, if the game is present at local, please backup the user content (like saves) inside the game dir. Downloading will overrite all conflicting files! 的本地化字符串。
        /// </summary>
        public static string BeforeDownloadInfo {
            get {
                return ResourceManager.GetString("BeforeDownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search via browser 的本地化字符串。
        /// </summary>
        public static string BrowserSearch {
            get {
                return ResourceManager.GetString("BrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compressing files... 的本地化字符串。
        /// </summary>
        public static string CompressingFilesProgress {
            get {
                return ResourceManager.GetString("CompressingFilesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Deletion 的本地化字符串。
        /// </summary>
        public static string ConfirmDeletion {
            get {
                return ResourceManager.GetString("ConfirmDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decompressing files... 的本地化字符串。
        /// </summary>
        public static string DecompressingFilesProgress {
            get {
                return ResourceManager.GetString("DecompressingFilesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Local 的本地化字符串。
        /// </summary>
        public static string DeleteLocal {
            get {
                return ResourceManager.GetString("DeleteLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected local game? This action cannot be undone. 的本地化字符串。
        /// </summary>
        public static string DeleteLocalWarning {
            get {
                return ResourceManager.GetString("DeleteLocalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Remote 的本地化字符串。
        /// </summary>
        public static string DeleteRemote {
            get {
                return ResourceManager.GetString("DeleteRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete the selected remote game? This action cannot be undone. 的本地化字符串。
        /// </summary>
        public static string DeleteRemoteWarning {
            get {
                return ResourceManager.GetString("DeleteRemoteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description: 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory Name: 的本地化字符串。
        /// </summary>
        public static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Docs 的本地化字符串。
        /// </summary>
        public static string Docs {
            get {
                return ResourceManager.GetString("Docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download complete 的本地化字符串。
        /// </summary>
        public static string DownloadCompleteProgress {
            get {
                return ResourceManager.GetString("DownloadCompleteProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading files... 的本地化字符串。
        /// </summary>
        public static string DownloadingFilesProgress {
            get {
                return ResourceManager.GetString("DownloadingFilesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Info 的本地化字符串。
        /// </summary>
        public static string EditInfo {
            get {
                return ResourceManager.GetString("EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable Name: 的本地化字符串。
        /// </summary>
        public static string ExecutableName {
            get {
                return ResourceManager.GetString("ExecutableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting files... 的本地化字符串。
        /// </summary>
        public static string ExtractingFilesProgress {
            get {
                return ResourceManager.GetString("ExtractingFilesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to download, see log for more detail. 的本地化字符串。
        /// </summary>
        public static string FailDownloadInfo {
            get {
                return ResourceManager.GetString("FailDownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to upload, see log for more detail. 的本地化字符串。
        /// </summary>
        public static string FailedToUpload {
            get {
                return ResourceManager.GetString("FailedToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Details 的本地化字符串。
        /// </summary>
        public static string GameDtails {
            get {
                return ResourceManager.GetString("GameDtails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Options 的本地化字符串。
        /// </summary>
        public static string GameOptions {
            get {
                return ResourceManager.GetString("GameOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to sync game save. Check config and See logs for more detail. 的本地化字符串。
        /// </summary>
        public static string GameSaveSyncFail {
            get {
                return ResourceManager.GetString("GameSaveSyncFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game save sync success! 的本地化字符串。
        /// </summary>
        public static string GameSaveSyncSuccess {
            get {
                return ResourceManager.GetString("GameSaveSyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Storage 的本地化字符串。
        /// </summary>
        public static string GameStorage {
            get {
                return ResourceManager.GetString("GameStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Bangumi Info 的本地化字符串。
        /// </summary>
        public static string GetBangumiInfo {
            get {
                return ResourceManager.GetString("GetBangumiInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get Bangumi info.See log for more info. 的本地化字符串。
        /// </summary>
        public static string GetBangumiInfoFail {
            get {
                return ResourceManager.GetString("GetBangumiInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get game icons 的本地化字符串。
        /// </summary>
        public static string GetIcon {
            get {
                return ResourceManager.GetString("GetIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get VNDB Info 的本地化字符串。
        /// </summary>
        public static string GetVNDBInfo {
            get {
                return ResourceManager.GetString("GetVNDBInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to get VNDB info.See log for more info. 的本地化字符串。
        /// </summary>
        public static string GetVNDBInfoFail {
            get {
                return ResourceManager.GetString("GetVNDBInfoFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Options 的本地化字符串。
        /// </summary>
        public static string GlobalOptions {
            get {
                return ResourceManager.GetString("GlobalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Game 的本地化字符串。
        /// </summary>
        public static string IgnoreGame {
            get {
                return ResourceManager.GetString("IgnoreGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Really want to ignore the game? If you want to get it back, delete .vngodignore under the game dir. 的本地化字符串。
        /// </summary>
        public static string IgnoreGameWarning {
            get {
                return ResourceManager.GetString("IgnoreGameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info refresh complete. 的本地化字符串。
        /// </summary>
        public static string InfoRefreshComplete {
            get {
                return ResourceManager.GetString("InfoRefreshComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing WebDAV in background... 的本地化字符串。
        /// </summary>
        public static string InitWebDAV {
            get {
                return ResourceManager.GetString("InitWebDAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Games 的本地化字符串。
        /// </summary>
        public static string LocalGames {
            get {
                return ResourceManager.GetString("LocalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This game does not have a Bangumi ID. 的本地化字符串。
        /// </summary>
        public static string NoBgmID {
            get {
                return ResourceManager.GetString("NoBgmID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save path not set! 的本地化字符串。
        /// </summary>
        public static string NoSavePath {
            get {
                return ResourceManager.GetString("NoSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Not Set] 的本地化字符串。
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This game does not have a VNDB ID. 的本地化字符串。
        /// </summary>
        public static string NoVNDBID {
            get {
                return ResourceManager.GetString("NoVNDBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log folder 的本地化字符串。
        /// </summary>
        public static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Repo 的本地化字符串。
        /// </summary>
        public static string OpenRepo {
            get {
                return ResourceManager.GetString("OpenRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An operation is in progress. Are you sure you want to close the window? The work will be running in background. 的本地化字符串。
        /// </summary>
        public static string OperationInProgressWarn {
            get {
                return ResourceManager.GetString("OperationInProgressWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other 的本地化字符串。
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password: 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play Time: 的本地化字符串。
        /// </summary>
        public static string PlayTime {
            get {
                return ResourceManager.GetString("PlayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preparing upload... 的本地化字符串。
        /// </summary>
        public static string PreparingUploadProgress {
            get {
                return ResourceManager.GetString("PreparingUploadProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process Name: 的本地化字符串。
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get missing Info 的本地化字符串。
        /// </summary>
        public static string RefreshInfo {
            get {
                return ResourceManager.GetString("RefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remote Games (Re-open the window to refresh) 的本地化字符串。
        /// </summary>
        public static string RemoteGames {
            get {
                return ResourceManager.GetString("RemoteGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rescan Games 的本地化字符串。
        /// </summary>
        public static string RescanGames {
            get {
                return ResourceManager.GetString("RescanGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run token test 的本地化字符串。
        /// </summary>
        public static string RunTokenTest {
            get {
                return ResourceManager.GetString("RunTokenTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Path: 的本地化字符串。
        /// </summary>
        public static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to select one of the exe. This will be remembered. 的本地化字符串。
        /// </summary>
        public static string SelectProcessTip {
            get {
                return ResourceManager.GetString("SelectProcessTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7-zip not found 的本地化字符串。
        /// </summary>
        public static string SevenZipNotFound {
            get {
                return ResourceManager.GetString("SevenZipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 7-zip Path 的本地化字符串。
        /// </summary>
        public static string SevenZipPath {
            get {
                return ResourceManager.GetString("SevenZipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting info refresh. 的本地化字符串。
        /// </summary>
        public static string StartingInfoRefresh {
            get {
                return ResourceManager.GetString("StartingInfoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting game save sync. 的本地化字符串。
        /// </summary>
        public static string StartingSync {
            get {
                return ResourceManager.GetString("StartingSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully downloaded and extracted! 的本地化字符串。
        /// </summary>
        public static string SuccessDownloadInfo {
            get {
                return ResourceManager.GetString("SuccessDownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully zipped and uploaded! 的本地化字符串。
        /// </summary>
        public static string SuccessfullyZippedAndUploaded {
            get {
                return ResourceManager.GetString("SuccessfullyZippedAndUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sync 的本地化字符串。
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Throw test exception 的本地化字符串。
        /// </summary>
        public static string ThrowTestException {
            get {
                return ResourceManager.GetString("ThrowTestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Unknown]  的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload complete 的本地化字符串。
        /// </summary>
        public static string UploadCompleteProgress {
            get {
                return ResourceManager.GetString("UploadCompleteProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uploading files... 的本地化字符串。
        /// </summary>
        public static string UploadingFilesProgress {
            get {
                return ResourceManager.GetString("UploadingFilesProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username: 的本地化字符串。
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VNDB 的本地化字符串。
        /// </summary>
        public static string VNDB {
            get {
                return ResourceManager.GetString("VNDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VNDB ID: 的本地化字符串。
        /// </summary>
        public static string VNDBID {
            get {
                return ResourceManager.GetString("VNDBID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VNDB Token: 的本地化字符串。
        /// </summary>
        public static string VNDBToken {
            get {
                return ResourceManager.GetString("VNDBToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV Configuration 的本地化字符串。
        /// </summary>
        public static string WebDAVConfig {
            get {
                return ResourceManager.GetString("WebDAVConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV initialize failed. Check your setting or network. See log for more information. 的本地化字符串。
        /// </summary>
        public static string WebDAVInitFailed {
            get {
                return ResourceManager.GetString("WebDAVInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV config Valid! 的本地化字符串。
        /// </summary>
        public static string WebDAVInitSuccess {
            get {
                return ResourceManager.GetString("WebDAVInitSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV not enabled. 的本地化字符串。
        /// </summary>
        public static string WebDAVNotEnabledWarn {
            get {
                return ResourceManager.GetString("WebDAVNotEnabledWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV metadata sync failed. See logs for more detail. 的本地化字符串。
        /// </summary>
        public static string WebDAVSyncFailed {
            get {
                return ResourceManager.GetString("WebDAVSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV metadata sync success! 的本地化字符串。
        /// </summary>
        public static string WebDAVSyncSuccess {
            get {
                return ResourceManager.GetString("WebDAVSyncSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WebDAV URL: 的本地化字符串。
        /// </summary>
        public static string WebDAVUrl {
            get {
                return ResourceManager.GetString("WebDAVUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to VNGod! It looks like this is your first time running a game. Please note that VNGod will hide during playing, and it will showup if you close the game. If that doesn&apos;t work properly, please edit the process name in &apos;edit info&apos;. If you have no idea how to use it, please see docs in settings! 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
